apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: wildcard-dev-digitoo-cz
 namespace: kube-system
spec:
 secretName: wildcard-dev-digitoo-cz
 issuerRef:
   name: letsencrypt-prod
   kind: ClusterIssuer
 dnsNames:
   - '*.dev.digitoo.cz'
   - '*.dev.digitoo.ai'
   - '*.dev.digitoo.sk'
